on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9
        
    - name: sync
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: sync

    - name: typecheck
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run mypy .
